server:
  port: 8080
  error:
    include-message: always

---

spring:
  profiles: default

axon:
  eventhandling:
    processors:
      order:
        mode: tracking

server:
  port: 8081
---

spring:
  profiles: docker

